/* Public domain. */

#ifndef	_LINUXKPI_LINUX_DMA_DATA_DIRECTION_H_
#define	_LINUXKPI_LINUX_DMA_DATA_DIRECTION_H_

enum dma_data_direction {
	DMA_BIDIRECTIONAL = 0,
	DMA_TO_DEVICE = 1,
	DMA_FROM_DEVICE = 2,
	DMA_NONE = 3,
};

#endif /* _LINUXKPI_LINUX_DMA_DATA_DIRECTION_H_ */
