/* Public domain. */

#ifndef _LINUXKPI_LINUX_MEDIA_BUS_FORMAT_H_
#define _LINUXKPI_LINUX_MEDIA_BUS_FORMAT_H_

#define MEDIA_BUS_FMT_FIXED 			1
#define MEDIA_BUS_FMT_RGB565_1X16		2
#define MEDIA_BUS_FMT_RGB666_1X18		3
#define MEDIA_BUS_FMT_RGB888_1X24		4
#define MEDIA_BUS_FMT_RGB666_1X24_CPADHI	5

#endif	/* _LINUXKPI_LINUX_MEDIA_BUS_FORMAT_H_ */
