/* Public domain. */

#ifndef _LINUXKPI_ASM_INTEL_FAMILY_H_
#define _LINUXKPI_ASM_INTEL_FAMILY_H_

#define	INTEL_ALDERLAKE		0x697
#define	INTEL_ALDERLAKE_L	0x69A
#define	INTEL_COMETLAKE		0x6A5
#define	INTEL_KABYLAKE		0x69E
#define	INTEL_KABYLAKE_L	0x68E
#define	INTEL_RAPTORLAKE	0x6B7
#define	INTEL_RAPTORLAKE_P	0x6BA
#define	INTEL_RAPTORLAKE_S	0x6BF
#define	INTEL_ROCKETLAKE	0x6A7

#endif /* _LINUXKPI_ASM_INTEL_FAMILY_H_ */
