/* Public domain. */

#ifndef _LINUXKPI_ASM_INTEL_FAMILY_H_
#define _LINUXKPI_ASM_INTEL_FAMILY_H_

#define	IFM(_fam, _model)	VFM_MAKE(X86_VENDOR_INTEL, _fam, _model)

#define	INTEL_ALDERLAKE			IFM(6, 0x97)
#define	INTEL_ALDERLAKE_L		IFM(6, 0x9A)

#define	INTEL_COMETLAKE			IFM(6, 0xA5)

#define	INTEL_KABYLAKE			IFM(6, 0x9E)
#define	INTEL_KABYLAKE_L		IFM(6, 0x8E)

#define	INTEL_RAPTORLAKE		IFM(6, 0xB7)
#define	INTEL_RAPTORLAKE_P		IFM(6, 0xBA)
#define	INTEL_RAPTORLAKE_S		IFM(6, 0xBF)

#define	INTEL_ROCKETLAKE		IFM(6, 0xA7)

#endif /* _LINUXKPI_ASM_INTEL_FAMILY_H_ */
